### ISSUE TITLE
Broken release

### ISSUE THREAD

**Issue by h3nnn4n** [repo-sync/pull-request#116]
I noticed that between yesterday and today, the action started breaking.

Looking at the release history I see that there is one that matches the timeframe when the action started failing here. I suspect that the latest release is broken, at least for my use case. 

The action doesn't provide any output, so I can't provide more information.

My action is:
```yaml
name: Create production PR

on:
  push:
    branches:
      - develop

jobs:
  createPR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "production"
          pr_title: "Production Deploy"
          pr_body: "Automated Production Deploy Pull Request. Opened with Github Actions. Merge this to trigger a deploy."
          pr_label: "Production Deploy"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
