### ISSUE TITLE
Is there any way to bring in the template from the .github/PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by credfeto** [repo-sync/pull-request#12]
As then this would automatically contain everything ready for filling out as part of the review.

**Comment by wei** [comment]
I'm open to it. we can use that file as pull request body if draft option is true #11 && body was not supplied. PR welcome.

**Comment by ChristophShyper** [comment]
I had the same issue.

My solution is to read template as a file and then use its content in pull request:

```
      - name: Read the template
        id: pr-template
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/PULL_REQUEST_TEMPLATE.md

      - name: Create pull request 
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_body: "${{ steps.pr-template.outputs.content }}"
          pr_title: "${{ github.event.commits[0].message }}"
```
