### ISSUE TITLE
fatal: unable to access <Git Repo URL>: The requested URL returned error: 400

### ISSUE THREAD

**Issue by brycnguyen** [repo-sync/pull-request#120]
With the new version 2.11, our github action is throwing a 400 error.

fatal: unable to access <Git Repo Url>: The requested URL returned error: 400

After we pinned the version to 2.9 it seem to work again.

repo-sync/pull-request@v2.9

**Comment by wei** [comment]
Thanks for the report, is there any way you can provide a url of the failed workflow run or some info on how the workflows is setup and if the repo is public/private, etc?

**Comment by brycnguyen** [comment]
It is a private repo so I cannot disclose too much:

```
      - name: Get the last person assigned the release
        uses: lee-dohm/last-assigned@v1
        with:
          query: 'label:weekly-release'
          token: ${{ secrets.GITHUB_TOKEN }}
        id: assigned

      - name: Get the list of people from the deploy team
        uses: lee-dohm/team-rotation@v1
        with:
          last: ${{ steps.assigned.outputs.last }}
          teamName: <some team name>
          token: ${{ secrets.TEAM_TOKEN }}
        id: rotation

      - name: Commit and create PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'staging'
          destination_branch: 'master'
          pr_title: <some title>
          pr_body: |
            <some body>
          pr_assignee: ${{ steps.rotation.outputs.next }}
          pr_draft: false
          github_token: ${{ secrets.TEAM_TOKEN }}
```

Here is the information I can give with redacting some info. We use this action to create a PR weekly and it uses lee-dohm/last-assigned@v1 and lee-dohm/team-rotation@v1 to get info for the pr_assignee, which both do not have any issues until we get to repo-sync/pull-request@v2

The TEAM_TOKEN has not changed for quite some time and still works with version 2.9.
