### ISSUE TITLE
Action stopped evaluating parameters as shell scripts

### ISSUE THREAD

**Issue by tbroadley** [repo-sync/pull-request#123]
Hello! First off, thanks for the great repo. My company uses this repo to automatically create PRs. Here's a snippet from one of our GitHub Actions:

```yaml
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: Update $(basename $(dirname $GITHUB_REF)) dependency to $(git rev-parse --short ${GITHUB_REF##*/})
```

Before about December 26, this would create PRs with names like "Update foo dependency to abc123". Now, this creates PRs with the literal name `Update $(basename $(dirname $GITHUB_REF)) dependency to $(git rev-parse --short ${GITHUB_REF##*/})`.

I suspect https://github.com/repo-sync/pull-request/pull/117 caused this repo to stop interpreting parameters like `pr_title` as shell scripts.
