### ISSUE TITLE
Getting error `Resource not accessible by integration`

### ISSUE THREAD

**Issue by thebishnu** [repo-sync/pull-request#129]
✖ Pull request command failed. This is the stderr output:
  Error creating pull request: Forbidden (HTTP 403)
  Resource not accessible by integration
  
  This is my workflow
```
on:
  push:
    branches:
    - "feature/*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Get CURRENT_BRANCH
      id: get_branch
      run:  echo ::set-output name=BRANCH::$(git symbolic-ref --short HEAD)

    - name: create pull request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "main"                      # If blank, default: master
        pr_title: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_reviewer: "dipendrachaudhary"                         # Comma-separated list (no spaces)
        pr_assignee: ${{ env.GIT_COMMIT_AUTHOR_NAME }}                         # Comma-separated list (no spaces)
        pr_label: "${{ env.GIT_COMMIT_AUTHOR_NAME }},${{ steps.get_branch.outputs.BRANCH }}"     # Comma-separated list (no spaces)
        pr_allow_empty: false                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Ebonsignori** [comment]
Based on the `403` the default token generated by the action workflow doesn't have sufficient permissions to read a resource. 

Could you see if it works when you add `permissions`?

```yml
on:
  push:
    branches:
    - "feature/*"  # Support wildcard matching

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request:
  # ...the rest of yml here
```

`permissions` is a relatively new security feature, see https://docs.github.com/en/actions/security-guides/automatic-token-authentication


If that doesn't work you'll want to [generate your own token](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and then add it to the [repo or org's secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) you're running this workflow from and set `github_token` to `${{ secrets.YOUR_SECRET_NAME }}`

I'm not certain what scopes you'll need, but if you figure it out we'd appreciate it if you shared your findings so we can update the docs with the scopes needed.
