### ISSUE TITLE
Repo to be archived, but README doesn't provide full replacement

### ISSUE THREAD

**Issue by theletterf** [repo-sync/pull-request#143]
The README example using `gh pr create` is incomplete. The `pull-request` action allowed to update existing sync PRs; this is not the case with `gh pr create`.

If the repo is going to be archived, will we be able to still use it? If not, what's a full replacement?

**Comment by theletterf** [comment]
@heiskr I initially replied in https://github.com/repo-sync/pull-request/issues/137, but opened an issue because, well, this should somehow get better closure.

**Comment by heiskr** [comment]
It looks like the CLI doesn't have an upsert, but something along the lines of `gh pr create || gh pr edit` I would think would work.

**Comment by theletterf** [comment]
@heiskr Would something like this work the same?

```
gh pr edit -B main || gh pr create -l "sync" -B main --title "Pulling ${{ github.ref }} into main" -H ${{ secrets.INTERMEDIATE_BRANCH }} -b "This PR synchronizes the public and private docs repo."
```

**Comment by heiskr** [comment]
I wonder if there's a nifty way in bash to share the arguments between the commands. It looks great to me though :) Pull request welcome

**Comment by theletterf** [comment]
This comes from @kov in https://github.com/cli/cli/discussions/5792#discussioncomment-3993375. I'm not actually sure it's a full replacement of the functionality. Would be nice to confirm; otherwise, only a fully fledged action can be a proper substitute.

**Comment by heiskr** [comment]
I'd think something like this could work, its two lines 🤷🏼 

```sh
gh_pr_up() { gh pr create $* || gh pr edit $* }
gh_pr_up --title "A new pull request" --body "Something"
```

**Comment by theletterf** [comment]
Added a patch in https://github.com/repo-sync/pull-request/pull/144

**Comment by theletterf** [comment]
This is what I was trying in my action:

```
gh pr edit -B main || gh pr create -l "sync" -B main --title "Pulling ${{ github.ref }} into main" -H ${{ secrets.INTERMEDIATE_BRANCH }} -b "This PR synchronizes the public and private docs repo."
```

Could it work like that?

**Comment by asteel-gsa** [comment]
Adding this here incase anyone wants to use it. I attempted to use `${{ github.event.number }}` for the PR# but had no such luck. Github Actions [Bot] when authoring the PR cannot invoke subsequent workflow calls (which we use to generate our terraform plan) hence the addition of our `pr-comment`. See [peter evans readme](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs) for more information.

However, I believe @heiskr answer would be the solution to edit the body of the pr when needed.

```yaml
  pull-request:
    name: Create Pull Request
    needs: [check-commit]
    if: ${{ needs.check-commit.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    outputs:
        pr_number: ${{ steps.pr-number.outputs.pull_request_number }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Current Date
        id: date
        run: |
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Get Git Short Commit
        id: git-short
        run: |
          echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Open Pull Request
        id: open-pr
        run: |
          gh pr create --label "label" --title "title" --body "body" --base base --head head

      - name: Get Pull Request Number
        id: pr-number
        run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        id: pr-comment
        run: |
          gh pr comment ${{ steps.pr-number.outputs.pull_request_number }} --body "body."
```
