### ISSUE TITLE
Refusing to fetch into current branch

### ISSUE THREAD

**Issue by bouteillerAlan** [repo-sync/pull-request#17]
Hello i have an error when the action is trigger :
![Screenshot_20200219_150827](https://user-images.githubusercontent.com/30547569/74841987-ec36cb80-5329-11ea-9596-fb6c1f547694.png)

step : 

1. create branch "test-auto-pr" from branch "develop"
2. create file `touch delete.me`
3. commit the file
4. push `git push origin test-auto-pr`
5. the job is trigger but is failed

My .yml : 
```yml
name: Create Pull Request
on:
  push:
    branches:
    - "*"
    - "!develop"
    - "!master"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"          # If blank, default: master
        pr_title: "${{github.actor}} triger auto pr : ${{ github.ref }} into develop"
        pr_body: "📡 *An automated PR*"  # Full markdown support, requires pr_title to be set
        pr_reviewer: "bouteillerAlan"             # Comma-separated list (no spaces)
        pr_assignee: "bouteillerAlan"             # Comma-separated list (no spaces)
        pr_label: "auto-pr"                   # Comma-separated list (no spaces)
        github_token: ${{ secrets.GITHUB_TOKEN }}

```
