### ISSUE TITLE
Double Quotes in `pr_body` break string

### ISSUE THREAD

**Issue by jakobo** [repo-sync/pull-request#27]
```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT }}
          pr_title: "⤴️ ${{ github.actor }} Draft Merge Request"
          pr_body: |
            :arrow_heading_up: Closes: #issueid <!-- your issue -->

            **Describe the Change** <!-- A longer description  -->
            "Put a description here"
          pr_draft: true
```

Expected: PR body is complete
Actual: PR body cuts off at `Put`, without the quotation marks

I think the cause for this is [the arg building for hub](https://github.com/repo-sync/pull-request/blob/master/entrypoint.sh#L54) which doesn't have any double quote protection. Unfortunately, there's not much that can be done. Either the pr_body allows `${{ expressions }}`, or it has to require `"` to be escaped. The current behavior requires `"` to be escaped, at which point we may just want to update the readme.
