### ISSUE TITLE
Action fails to run with `fatal: bad revision` error being thrown

### ISSUE THREAD

**Issue by jamesrweb** [repo-sync/pull-request#64]
Currently when CI runs it fails with a `fatal: bad revision 'refs/pull/351/merge'` error. This seems strange because every other workflow that is ran such as our build workflow doesn't have any issues, only this workflow and specifically only the `repo-sync/pull-request` step of this wokflow fail.

Here is an outline of the failing workflow:

```yaml
name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.1.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
      - uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - uses: atlassian/gajira-find-issue-key@master
        id: jira-issue-number
        with:
          from: branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: repo-sync/pull-request@v2
        with:
          pr_title: "Omitted"
          pr_body: "Omitted"
          pr_reviewer: "Omitted"
          pr_label: "Omitted"
          github_token: ${{ secrets.GH_TOKEN }}
```

All the other steps pass fine as you can see here:

<img width="1394" alt="Bildschirmfoto 2021-07-05 um 15 03 32" src="https://user-images.githubusercontent.com/47126579/124475615-334c2200-dda2-11eb-89d5-d595e3dbf3be.png">

Any help would be much appreciated!
