### ISSUE TITLE
Create new branch for merge

### ISSUE THREAD

**Issue by bbugh** [repo-sync/pull-request#66]
Hi! 👋 Great action, thank you for making it.

We have a situation where our development branch only allows squash merges, and our main branch cannot be committed to directly. When we create a pull request from `main` -> `development` and there's any conflict, we cannot fix the conflict and have to manually create another pull request. 

Would you accept a PR to add a feature to create an intermediary branch? Something like:

```yaml
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ env.TARGET }}
        branch_name: ${{ env.BRANCH_NAME }}  # 🆕 Add input for branch name
```

This would create a branch from `source_branch` named `branch_name` that targets `destination_branch`. 

The script would simply create the branch name from the source branch and push it before running the `hub` command.
