### ISSUE TITLE
Subsequent workflows will not be executed.

### ISSUE THREAD

**Issue by satodaiki** [repo-sync/pull-request#70]
hi there.

I created a workflow using this actions, but the workflow I already created is no longer executed.

Workflow that is executed when pull_request is created in develop and main. An example is shown below.

```yaml
name: example

on:
  workflow_run:
    workflows: ["Create Pull Request"]
    types:
      - completed
  pull_request:
    branches:
      - main
      - develop

jobs:
...
```

The workflow using `repo-sync/pull-request` looks like this.

```yaml
name: Create Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    name: create-pull-request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "[example] test_summary"
          pr_body: "test body."
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

If you know any solution, please let me know.

I look forward to working with you : )
