### ISSUE TITLE
Subsequent Workflows Don't Execute when NOT USING secrets.GITHUB_TOKEN

### ISSUE THREAD

**Issue by CreepyGnome** [repo-sync/pull-request#71]
We use the https://github.com/tibdex/github-app-token to generate a token so we can have a workflow trigger another workflow etc etc.

However when we use that generated token with this PR Action it creates the PR but none of the workflows are triggered for that PR, it's as if it used the `secrets.GITHUB_TOKEN` somehow and not the one generated in the generate-token step.  We use that generate token process in other workflows without issues, this is the first time we are using it in a workflow that was already using this PR action. 

We even created a personal access token, just to test this, and the same thing happens with this action it creates the PR but non of the workflows for the PR run.

We have a step like this:
```
- name: Generate Token
   uses: tibdex/github-app-token@v1
   id: generate-token
   with:
     app_id: ${{ secrets.GENERATED_TOKEN_APP_ID }}
      private_key: ${{ secrets.GENERATED_TOKEN_APP_PRIVATE_KEY }}  
```

Then we run the PR action like this:
```
- name: Create Pull Request
   id: open-pr
   uses: repo-sync/pull-request@v2
   with:
     source_branch: ${{ steps.release_name.outputs.branch }}
     destination_branch: master
     pr_title: Release ${{ steps.release_name.outputs.name }}
     pr_body: ${{ steps.read_file.outputs.contents}}
     pr_label: release
     github_token: ${{ steps.generate-token.outputs.token }}
```
