### ISSUE TITLE
could not find any git remote pointing to a GitHub repository

### ISSUE THREAD

**Issue by craigbryson** [repo-sync/pull-request#76]
Hi!

I'm experiencing this error when running the action:

`could not find any git remote pointing to a GitHub repository`

The action reports success but a PR is not created - I have noticed that if I re-run the job from the UI it is successful and creates the PR.

Below is a snippet of my configuration and logs

```yaml
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "craigbryson"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

```bash
From https://github.com/myOrg/myRepo
11
 * [new branch]      main       -> main
12
 * [new branch]      main       -> origin/main
13
* core-image-updates                3cf280d [origin/core-image-updates] **Automated image update**
14
  main                                   26fbf22 Update nginx-ingress.yaml
15
  remotes/origin/core-image-updates 3cf280d **Automated image update**
16
  remotes/origin/main                    26fbf22 Update nginx-ingress.yaml
17
hub pull-request   -b main   -h core-image-updates   --no-edit   -m "Pulling refs/heads/core-image-updates into main" -m "👑 *An automated PR*" -r "craigbryson" -d   || true
18
Aborted: could not find any git remote pointing to a GitHub repository 
```

Am I going wrong somewhere?
