### ISSUE TITLE
Can I have the github-actions bot be the actor?

### ISSUE THREAD

**Issue by mbongard** [repo-sync/pull-request#78]
Hi,
I was wondering if it is possible to have the github-actions bot be the one who creates the PR and adds the labels to it.
Currently it just uses my own name...

<img width="310" alt="image" src="https://user-images.githubusercontent.com/32648275/158282593-afeff725-32e6-4cf9-b705-aa4f79f57592.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/32648275/158282618-0018934b-121f-4588-acaf-bd655103ce25.png">

Anyone have an idea on how I can achieve this?

**Comment by wei** [comment]
Hi @mbongard thanks for the issue. The user is determined by the `github_token`. If you use `github.token` then it will use github-actions as the user. If you use PAT, it will use the user of the PAT~

**Comment by dgokcin** [comment]
@mbongard hello, I am trying to extend this action to also merge after the auto pr. how exactyl did you accomplish that in the screenshot you have shared above? which action are you using and do you mind sharing it?

thanks!

**Comment by mbongard** [comment]
Hi @dgokcin,
I am using the action `pascalgn/automerge-action` to automerge. The action requires to have `branch protection rules` enabled in your repo settings. From their [README](https://github.com/pascalgn/automerge-action):

>When added, this action will run the following tasks on pull requests with the automerge label:
>
> Changes from the base branch will automatically be merged into the pull request (only when "Require branches to be up to date before merging" is enabled in the branch protection rules)
When the pull request is ready, it will automatically be merged. The action will only wait for status checks that are marked as required in the branch protection rules
Pull requests without any configured labels will be ignored

So create a `branch protection rule` in `your-repo > Settings > Branches` for the target branch and enable the setting like this:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/32648275/163111527-f6913f36-bcd0-4a1c-8be8-fbb9e7397855.png">

My full GitHub action workflow file to automerge `dev` into `main`:

```yaml
name: Merge To Main

on: workflow_call
  
jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create-pull-request
        id: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: main
          pr_title: "Auto-Generated PR: dev -> main"
          pr_label: "automerge"
          pr_allow_empty: true
          github_token: ${{ github.token }}
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          PULL_REQUEST: "${{ steps.create-pull-request.outputs.pr_number }}"
```
