### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by dgokcin** [repo-sync/pull-request#84]
Hello and thank you for this action. Although I am using the same workflow in a different repository in the same organization, I am having an interesting error in a single repository. Here is my workflow and the error that I am having. Any idea what might be going on?

```
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```
![image](https://user-images.githubusercontent.com/33603535/163060974-dcabf7e2-768e-4c1a-9669-1dcec5ca2325.png)

```yaml
name: auto create PR to develop
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        if: github.event.pull_request.merged == true
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.head_ref }}
          destination_branch: "develop"
          pr_title: ${{ format('Auto PR from {0}', github.head_ref) }}
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

```

**Comment by EvanBoyle** [comment]
+1, just started running into this

**Comment by vvanghelle** [comment]
Facing same issue here. Was working fine few hours ago

**Comment by rileymiller** [comment]
just broke for us too

**Comment by mikesurowiec** [comment]
This is likely related to https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by cea2aj** [comment]
> This is likely related to https://github.blog/2022-04-12-git-security-vulnerability-announced/

+1. It looks like the git version being used is 2.35.2 since the 'safe.directory' variable in the error message wasn't added until that version

**Comment by lcnlvrz-revelacion** [comment]
same here

**Comment by brandonkoch3** [comment]
+1 here as well.  Is there any means of working around this, as the suggestion to call `git config --global --add safe.directory /github/workspace` seems to be client-side, and would have no bearing on an automated action running a workflow.

**Comment by mwaddell** [comment]
+1 here as well - just started happening a few hours ago

**Comment by dgokcin** [comment]
anyone with a work around? we are using this action in almost all of our repositories to create prs once there is a hotfix. i really do not want to do that manually.

**Comment by cea2aj** [comment]
As a workaround, you can copy the [entrypoint.sh](https://github.com/repo-sync/pull-request/blob/5ba2c80b97c87b9174c1548141b7acd80f6376e1/entrypoint.sh) script into your repo (for example, in the .github folder), and add then `git config --global --add safe.directory /github/workspace` near the top. [Here](https://github.com/repo-sync/pull-request/blob/84eb0c3478f13651e5649367941b867ca02d7926/entrypoint.sh) is an example of the updated script. Then you can point the GH action to the script:
```yml
uses: repo-sync/pull-request@v2
with:
  entrypoint: './.github/entrypoint.sh'
  pr_title: "PR Title"
  github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by razatta** [comment]
> As a workaround, you can copy the [entrypoint.sh](https://github.com/repo-sync/pull-request/blob/5ba2c80b97c87b9174c1548141b7acd80f6376e1/entrypoint.sh) script into your repo (for example, into a folder such as .github/pull-request), and then add `git config --global --add safe.directory /github/workspace` near the top. [Here](https://github.com/repo-sync/pull-request/blob/84eb0c3478f13651e5649367941b867ca02d7926/entrypoint.sh) is an example of the updated script. Then you can point the GH action to the script:
> 
> ```yaml
> uses: repo-sync/pull-request@v2
> with:
>   entrypoint: './.github/pull-request/entrypoint.sh'
>   pr_title: "PR Title"
>   github_token: ${{ secrets.GITHUB_TOKEN }}
> ```

this did not work ! did any body else got a fix for it?

**Comment by dgokcin** [comment]
@razatta I cloned the action.yml, dockerfile, entrypoint etc. that @cea2aj did in [this pr](https://github.com/cea2aj/pull-request/tree/dev/unsafe-repo-fix) to a internal github actions repository that we are using to store custom actions. I than modified my existing workflow to use that action instead of the original one.

```
name: auto create PR to develop
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  pull-request:
    name: "auto merge PR to develop"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Checkout Navlungo GitHubActions Repository
        uses: actions/checkout@v2
        with:
          repository: MyOrg/GitHubActions
          token: ${{ secrets.PAT }}
          ref: main
          path: .github/actions

      - name: Auto Create PR
        id: create-pr
        uses: ./.github/actions/pull-request
        with:
          source_branch: ${{ github.head_ref }}
          destination_branch: "develop"
          pr_title: ${{ format('Auto PR from {0}', github.head_ref) }}
          pr_label: "automerge"
          github_token: ${{ github.token }}
```

**Comment by eleni-salamani** [comment]
+1 here as well - started hitting us a couple of hours ago

**Comment by sdapkus** [comment]
Thanks to @cea2aj I've updated my Workflow file -
instead of
```yaml
- uses: repo-sync/pull-request@v2
```
using
```yaml
- uses: cea2aj/pull-request@84eb0c3478f13651e5649367941b867ca02d7926
```

Not the best solution, but until it is not merged, it's a workaround

**Comment by forana** [comment]
Could this be reopened? This issue is not solved.

**Comment by GretcorpMultimedia** [comment]
I had the same issue and solved it by doing the following steps.

If anyone is stll facing this, and is using visual studio, 
uninstall the github extension for windows, 
then the extention for visual studio, 
restart and install the githb for windows directly from github, 
open your repository folder and follow the instructions on screen 

this will enable you to fix any issues you experience using the desktoop app, without having to do any work arounds.

if you have an older version of github for windows,  until Microsoft update the extension for windows it wont work.

**Comment by bdelanghe** [comment]
I know this issue is closed but I was hoping to get some help. Currently still running into the issue:

I have a fork that is currently up to date https://github.com/bdelanghe/pull-request

This is my current action setup:
```
name: Create PR

on:
  push:
    branches-ignore: [ main ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: bdelanghe/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: ":crown: *An automated PR*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
The console output for the container hasn't given me much insight. Figure I'm just missing something obvious.
