### ISSUE TITLE
Ability to re-request review

### ISSUE THREAD

**Issue by bomb-on** [repo-sync/pull-request#9]
Is it possible to automatically trigger "Re-request review" in case that PR was approved by reviewer but new code was committed **after approval** and **before merging**?

For example, my `.yml` file has following configuration:

```
on:
  push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "${{github.actor}} - Pulling ${{ github.ref }} into develop"
          pr_reviewer: "bomb-on"
          pr_assignee: "bomb-on"
          pr_label: "auto-pr"
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

Let's say that one of the repository contributors creates a new feature branch and pushes it:
```
git flow feature start 'test-feature-1'
echo "feature1" > feature1
git add .
git commit -m "First Feature"
git push --set-upstream origin feature/test-feature-1
```
The PR will be created and assigned for review. I do review and approve it but I don't merge it immediately. At this point, same user updates the same branch, e.g.:
```
echo "update" >> feature1
git add .
git commit -m "First Feature Update"
git push
```
This commit will end up in the same PR and I can see that there has been changes in GitHub's PR page:
![Screenshot 2019-11-08 at 14 04 14](https://user-images.githubusercontent.com/1420287/68482108-b6fde600-0230-11ea-9bdd-29052f5fb1d7.png)
but it won't trigger "Re-request review" and it will look like updated code has been reviewed and whole PR approved.

So, is it possible to somehow automatically trigger this "Re-request review" in such case?
