### ISSUE TITLE
Problems with self-hosted runners

### ISSUE THREAD

**Issue by tegorov** [repo-sync/pull-request#91]
There are two problems with self-hosted runners:
1) Every run creates a new docker image.
2) A container is run as root user, that causes some problems with the files in future runs

The first problem is solved by building a docker image and referencing it in a workflow:
```yaml
- name: 'Create pull request'
  uses: docker://ghcr.io/tegorov/pull-request:v2.6.2
  with:
     source_branch: develop
  ...
```
The second problem is solved by passing USER_ID parameter in a container:

```yaml
- name: 'Create pull request'
  uses: docker://ghcr.io/tegorov/pull-request:v2.6.2
  with:
     source_branch: develop
     ...
  env:
     USER_ID: 1000
```
Here is my pull request as an example https://github.com/repo-sync/pull-request/pull/90

**Comment by wei** [comment]
Fixed https://github.com/repo-sync/pull-request/blob/992f4d71681e87fe325632f2ed0eaaf8f08347ef/action.yml#L52-L54

**Comment by tegorov** [comment]
@wei thanks, but you fixed only the first problem.
This pr #90 fixes the second problem.

**Comment by wei** [comment]
Can you elaborate 

> causes some problems with the files in future runs

**Comment by tegorov** [comment]
> Can you elaborate and provide reproduction steps?

When a container runs, it uses the root user by default, that new files created in a container will be added to a runner with root user permissions.
After the first run, next runs will fail at this step:
`- uses: actions/checkout@v3` 
because a runner is using a different user (not root) and can not clear files with root permission (`git clean`)
```yaml
jobs:
  pull-request:
    runs-on: [ self-hosted, Linux ]
    steps:
    - uses: actions/checkout@v3
    - uses: docker://ghcr.io/repo-sync/pull-request:v2.8 
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
