### ISSUE TITLE
source and destination branches are the same but not

### ISSUE THREAD

**Issue by havok2063** [repo-sync/pull-request#92]
I'm trying to use this action to auto create a PR triggered off a branch name into `master`, basically the exact same example given in the docs.  However, when the action runs, it says the `Source and destination branches are the same.` and does not create the PR.  I'm trying to trigger from source branch `dm_update_tree` to destination branch `master`.    My workflow looks like the following:

```
name: Add New Paths

on:
  push:
    branches:
      - dm_update_tree

jobs:
  createpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""
          destination_branch: "master"
          pr_title: "New tree paths"
          pr_body: ":crown: *An automated PR*"
          pr_reviewer: "havok2063"
          pr_label: "auto-pr,enhancement"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output PR URL
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: Output PR Number
        run: echo ${{steps.open-pr.outputs.pr_number}}
```

**Comment by leonbusse** [comment]
I have the same problem with this test config.
```
on:
  push:
    branches: [ "feature-1" ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev"
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
